version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_KEY: test2  # 👈 ส่งค่าเข้า Docker build
    ports:
      - "5000:80"
    restart: unless-stopped
